name: Lint incoming Git commits
author: Emphori
description: A GitHub Action to help maintain a consistent Git history
branding:
  icon: git-pull-request
  color: green

inputs:
  git-target-branch:
    description: The target branch against which the log will be built
    default: ${{ github.base_ref }}
  git-source-branch:
    description: The source branch from which the log will be derived
    default: ${{ github.head_ref }}
  git-commit-grep:
    description: The pattern to be used to validate incoming commit messages

runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/git-lint-commits.sh "${{ inputs.git-commit-grep }}" "${{ inputs.git-target-branch }}"
      shell: bash
